name: flutter_donate_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0

  # Utils
  intl_phone_number_input: ^0.7.4
  flutter_floating_bottom_bar: ^1.2.0

  # Localization
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/svg/
    - assets/images/png/
    - assets/images/lotties/
    - assets/fonts/

  fonts:
    - family: InterFontFamily
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf