name: flutter_donate_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2

  # Utils
  intl_phone_number_input: ^0.7.4
  image_picker: ^1.1.1
  carousel_slider: ^4.2.1
  toastification: ^2.0.0
  shimmer: ^3.0.0
  csc_picker: ^0.2.7

  # Core
  equatable: ^2.0.5
  photo_manager: ^3.1.1
  connectivity_plus: ^6.0.3
  photo_view: ^0.15.0

  # Network
  http: ^1.2.1
  url_launcher: ^6.1.8
  cached_network_image: ^3.3.1

  # Permission
  permission_handler: ^11.3.1

  # Location
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  # Router
  go_router: ^14.1.3

  # Dependency Injection
  get_it: ^7.7.0

  # Localization
  easy_localization: ^3.0.7

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # State Management
  flutter_riverpod: ^2.5.1

  # Firebase
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.16.0
  firebase_storage: ^11.7.0
  firebase_crashlytics: ^3.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # ------------- <ASSETS> ------------- #
  assets:
    - assets/lang/
    - assets/images/svg/
    - assets/images/png/
    - assets/images/lotties/
    - assets/fonts/

  # ------------- <FONTS> ------------- #

  fonts:
    - family: InterFontFamily
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
